DROP TABLE IF EXISTS recipes CASCADE;
CREATE TABLE recipes(
    Name VARCHAR(100) CHARACTER SET,
    Rating VARCHAR(10) CHARACTER SET,
    Ease_of_Prep VARCHAR(14) CHARACTER SET,
    Prep_Time VARCHAR(10) CHARACTER SET,
    Main_Ingredients VARCHAR(100) CHARACTER SET
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    username VARCHAR(50) PRIMARY KEY,
    password CHAR(60) NOT NULL
);