INSERT INTO recipes (Name, Rating, Ease_of_Prep, Prep_Time, Main_Ingredients) VALUES 
    ('Jamaican Jerk Chicken','5','Average',30,'Chicken'),
	('Pasta Salad','3','Fairly Easy',20,'Kielbasa,Noodles'),
	('Lasagna','3','Fairly Easy',45,'Sausage,Noodles'),
	('Hearty Pancakes','4','Average',20,'Milk,Eggs,Corn Meal'),
	('Summer Garden Couscous Salad','4','Hard',30,'Vegetarian'),
	('Squash Corn Chowder','3','Hard',45,'Vegetarian,Potatoes'),
	('White beans, tomatoes, and spinach','4','Fairly Easy',30,'Rice,Vegetarian,Beans,Eggs'),
	('Spaghetti','5','Super Simple',15,'Noodles,Marinara Sauce'),
	('Scones','5','Super Simple',45,'Wheat,Eggs,Baking Powder'),
	('Pizza','5','Average',120,'Sausage,Cheese'),
	('Stir-Fry','5','Fairly Easy',25,'Chicken,Rice'),
	('Rustic Italian Tortellini Soup','4','Hard',30,'Sausage,Noodles,Cheese'),
	('Swedish Meatballs','4','Very Difficult',90,'Beef,Noodles,Eggs'),
	('Barley Beef Skillet','5','Super Simple',25,'Beef'),
	('Southwest Beef & Rice Skillet','5','Super Simple',25,'Beef,Rice,Beans'),
	('Glazed Pork Chops with Corn Bread Dressing','4','Average',45,'Pork'),
	('Fried Rice','4','Super Simple',20,'Chicken,Eggs,Rice'),
	('Zesty Sausage & Beans','5','Fairly Easy',45,'Sausage,Beans,Rice'),
	('Prosciutto Pasta Toss','2','Fairly Easy',30,'Noodles,Ham'),
	('Cashew Chicken with Noodles','5','Average',20,'Noodles,Chicken'),
	('Herb Chicken with Honey Butter','3','Average',30,'Chicken'),
	('French Toast','4','Super Simple',10,'Eggs'),
	('Swedish Pancakes','4','Fairly Easy',20,'Milk,Eggs'),
	('Baked Cheddar Eggs & Potatoes','5','Fairly Easy',45,'Potatoes,Bacon,Cheese,Eggs'),
	('Baked Mostaccioli','5','Super Simple',90,'Noodles,Marinara Sauce,Cheese,Sausage'),
	('Ravioli with Snap Peas','4','Hard',40,'Noodles,Milk,Cheese'),
	('Cloverleaf Rolls','3','Fairly Easy',30,'Milk'),
	('Greek Yogurt and Honey Blueberry Muffins','4','Average',30,'Eggs,Milk'),
	('Whole Grain Waffles','5','Super Simple',25,'Eggs,Milk'),
	('Lemon Bars','3','Fairly Easy',60,'Lemons,Flour,Eggs,Butter'),
	('Qahaq Cookies','2','Average',30,'Butter, Eggs'),
	('Blondies with Nutella','2','Hard',90,'Eggs, Butter'),
	('Hot Chocolate','5','Super Simple',10,'Milk'),
	('Chocolate Mousse','4','Hard',30,'Eggs'),
	('Smores Cookie Bars','4','Hard',45,'Marshmellows, Chocolate'),
	('Orange Chicken','4','Fairly Easy',40,'Chicken,Rice'),
	('Tostadas','3','Super Simple',20,'Chicken,Cheese'),
	('Black Bean Stuffed Sweet Potatoes','1','Fairly Easy',20,'Beans,Cheese'),
	('Asian Shredded Beef','5','Super Simple',30,'Beef,Noodles'),
	('Capellini with sausage, spinach, and jalapeno','4','Fairly Easy',40,'Sausage,Noodles'),
	('Crispy Chicken with Kale','2','Fairly Easy',45,'Chicken'),
	('Roast Chicken Grain Bowl','1','Average',60,'Chicken'),
	('Chicken thighs with barley and peas','2','Fairly Easy',60,'Chicken'),
	('Rice noodles with meatballs and bok choy','4','Hard',45,'Beef,Noodles'),
	('Paprika Pork with Roasted Potatoes and Dill Cream','3','Fairly Easy',60,'Pork,Potatoes'),
	('Chicken cutlets with carrot and kale salad','3','Average',30,'Chicken'),
	('Gnocchi and sweet potatoes','3','Fairly Easy',20,'Potatoes, Flour, Eggs'),
	('Shepherd''s Pie','4','Hard',60,'Beef,Potatoes'),
	('Garlic Parmesan Chicken','2','Super Simple',45,'Chicken,Rice'),
	('Turkey Pot Pie','3','Fairly Easy',60,'Turkey'),
	('Balsamic Bacon Brussels Sprouts','3','Fairly Easy',40,'Bacon'),
	('Lemon Red Potatoes','2','Super Simple',150,'Potatoes'),
	('Potato and Corn Chowder','3','Super Simple',20,'Potatoes,Milk,Cheese'),
	('Thai Chicken','5','Super Simple',30,'Chicken,Noodles,Eggs'),
	('Italian Fagoli Vegetable Soup','4','Fairly Easy',45,'Vegetarian,Beans,Noodles'),
	('Blueberry Pie','5','Fairly Easy',120,'Blueberries, Flour'),
	('Chocolate Pudding','4','Fairly Easy',30,'Milk, Eggs, Cocoa Powder'),
	('Browned Butter Beets','5','Hard',120,'Beets,Breadcrumbs'),
	('Turkey Soup with Homemade Noodles','4','Average',120,'Turkey,Noodles'),
	('Home fries','5','Super Simple',45,'Potatoes'),
	('Chocolate Raspberry Torte','5','Hard',60,'Eggs,Milk'),
	('Golden Latte','5','Super Simple',20,'Milk'),
	('Fig Shake','4','Fairly Easy',10,'Milk'),
	('Lentil Soup','3','Average',60,'Lentils,Vegetarian,Carrots,Onion'),
	('Buckwheat Tabboulah','1','Super Simple',30,'Buckwheat,Vegetarian,Carrots,Onion'),
	('Lentil Rice Bowls with Egg','4','Fairly Easy',60,'Rice,Lentils,Onion'),
	('Italian Vegetable Lentil Soup','4','Fairly Easy',60,'Lentils,Onion,Vegetarian'),
	('One Pot Chicken & Potatoes','4','Super Simple',90,'Potatoes,Chicken,Carrots,Onion'),
	('Sweet Korean Lentils','5','Fairly Easy',45,'Lentils,Rice,Onion'),
	('Buckwheat Beetroot Salad','3','Average',60,'Beets,Buckwheat'),
	('New Potato Lentil Salad','4','Fairly Easy',50,'Potatoes,Lentils'),
	('Ham & Potato Soup','4','Average',60,'Potatoes,Ham,Onion,Milk'),
	('Lemon Dill Potatoes','4','Super Simple',50,'Potatoes'),
	('BBQ Lentils','3','Fairly Easy',60,'Lentils,Rice'),
	('Healthy Buckwheat Soup','3','Super Simple',45,'Buckwheat,Carrots,Onion'),
	('Buckwheat Chicken Pilaf','5','Hard',120,'Buckwheat,Carrots,Chicken,Onion'),
	('Vegetable Noodle Soup','4','Super Simple',40,'Carrots,Noodles'),
	('Bacon and Honey Potato Salad','3','Fairly Easy',45,'Potatoes,Bacon'),
	('Pretzel Sticks','4','Average',60,'Eggs,Flour,Yeast'),
	('Golden French Lentil Soup','3','Fairly Easy',60,'Lentils'),
	('Lentil Shepherd''s Pie','5','Average',90,'Lentils,Carrots,Onion,Peas,Potatoes'),
	('Honey Lime Chicken','3','Fairly Easy',45,'Chicken,Rice'),
	('Lentil Curry','2','Super Simple',45,'Lentils,Carrots,Onion'),
	('Dutch Oven Bread','5','Super Simple',60,'Flour,Yeast'),
	('Potato Apple Roast','4','Average',45,'Apple,Potatoes,Ham'),
	('Baking Powder Biscuits','3','Super Simple',30,'Flour,Milk,Eggs'),
	('Sugar Cookies','5','Fairly Easy',25,'Flour,Eggs'),
	('Potato Curry','4','Fairly Easy',35,'Potatoes,Vegetarian'),
	('Bucatini all''Amatriciana','4','Hard',45,'Noodles,Tomatoes,Bacon'),
	('Brioche Chocolate Rolls','4','Fairly Easy',120,'Flour,Eggs,Yeast,Fish'),
	('Naan','5','Fairly Easy',45,'Milk,Yogurt,Flour,Yeast'),
	('Lemon Poppy Seed Scones','5','Super Simple',30,'Flour,Butter,Sour Cream'),
	('Balsamic Dijon Root Vegetables','4','Fairly Easy',150,'Potatoes,Onion,Carrots,Parsnips'),
	('Best Baked Chicken Legs','5','Super Simple',90,'Chicken,Rice'),
	('Spanish Lentil Soup','3','Fairly Easy',60,'Ham,Lentils'),
	('Chocolate Chip Irish Soda Bread','2','Average',60,'Flour,Chocolate Chips'),
	('Malteese Gilatti','2','Average',120,'Flour,Butter,Yeast'),
	('Buckwheat Carrot and Onion','4','Fairly Easy',40,'Buckwheat,Carrots,Onion'),
	('Sweet Potatoes with Yogurt and Chickpeas','5','Fairly Easy',30,'Chickpeas,Potatoes,Yogurt,Eggs'),
	('Spanish Chickpeas','5','Average',45,'Chickpeas,Flour,Yogurt,Onion,Eggs'),
	('Lemon Fettuchini','4','Fairly Easy',30,'Noodles,Coconut milk'),
	('Chickpea Masala','5','Fairly Easy',40,'Chickpeas,Flour,Yogurt,Eggs'),
	('Chickpea Broccoli Pesto','3','Super Simple',40,'Broccoli,Chickpeas'),
	('Thai Veggie Soup','3','Average',30,'Coconut milk,Noodles'),
	('Buttery Herb Chicken','4','Fairly Easy',20,'Chicken,Rice'),
	('Rosemary Parsnips','5','Super Simple',35,'Parsnips'),
	('Balsamic Potatoes and Asparagus','3','Super Simple',40,'Potatoes,Asparagus'),
	('Quinoa Brussels Sweet Potato Salad','4','Average',40,'Quinoa,Brussels Sprouts ,Sweet potato'),
	('Thai Peanut Cabbage Quinoa','4','Fairly Easy',20,'Quinoa,Cabbage,Peanut'),
	('Lemon Garlic Asparagus with Orzo','3','Average',30,'Orzo,Asparagus'),
	('Moroccan Sweet Potato Lentil Stew','3','Average',60,'Sweet potato,Lentils,Spinach,Onion,Carrots'),
	('Chia Crusted Salmon','4','Fairly Easy',20,'Salmon,Chia'),
	('Pinto Beans and Tomatillo Cilantro Lime Rice','5','Hard',60,'Beans,Rice,Onion,Tomatillo,Lime,Garlic'),
	('Thai Squash Soup','3','Average',60,'Squash,Coconut milk,Peanut,Onion,Garlic,Carrots,Cilantro'),
	('Roasted Carrot & Peanut Sauce','5','Average',75,'Carrots,Peanut,Cilantro'),
	('Majoram White Wine Chicken','4','Average',120,'Chicken,Wine'),
	('Marjoram Carrots','5','Fairly Easy',30,'Carrots,Garlic'),
	('Soy Mustard Salmon','4','Fairly Easy',20,'Salmon,Soy Sauce,Dijon Mustard,Garlic,Ginger'),
	('Mango Chutney','3','Average',30,'Mango,Cheese,Apple,Raisins,Bell Pepper,Jalopeno Pepper'),
	('Vegetarian Chili','3','Fairly Easy',25,'Vegetarian,Tomatoes'),
	('Sweet Potato Breakfast Burritos','4','Average','45','Sweet potato'),
	('Roasted Sweet Potato Lentil Salad','5','Fairly Easy',45,'Lentils,Sweet potato,Spinach,celery'),
	('Cornbread','3','Fairly Easy',40,'Butter,Milk,Flour,Corn Meal,Baking Powder'),
	('Brussel Honey Lentil Quinoa','3','Fairly Easy',25,'Brussels Sprouts ,Quinoa,Lentils,Onion'),
	('Lentil Sweet Potato Curry','4','Average',60,'Sweet potato,Apple,Lentils,Onion,Garlic,Tomatoes,Rice'),
	('Gnocci and white beans','4','Average',30,'Beans,Spinach,Tomatoes,gnocchi,Cheese'),
	('Pad Thai','3','Fairly Easy',30,'Vegetarian,Noodles'),
	('Kung Pao Chicken','2','Fairly Easy','30','Chicken,Peanut,Water chestnuts'),
	('Mediterranean Tuna Steaks','3','Fairly Easy',20,'Tuna,Capers'),
	('Tomato Basil Soup','4','Average',45,'Tomatoes,Basil'),
	('Chewy Chocolate Chip COokies','5','Fairly Easy',30,'Butter,Chocolate Chips,Flour'),
	('Quinoa Peanut Kale Curry','4','Average',45,'Quinoa,Kale,Peanut,Cilantro,Onion,Coconut milk'),
	('Sweet Potato Lentil Curry with Pickled Onion','4','Average',60,'Sweet potato,Red onion,Lentils,Ginger,Coconut milk,Cilantro'),
	('Sardine Mediterranean Pasta','3','Fairly Easy',30,'Sardine,Capers,Shallots,Lemon,Parsley'),
	('Prosciutto apple flatbread pizza','3','Fairly Easy',45,'Apple,Prosciutto,Cheese'),
	('Dill Cucumber Salmon','4','Average',30,'Fish,Yogurt,Cucumber,Dill,Broccoli,Red onion'),
	('Vegetable Couscous','5','Hard',60,'Couscous,Green Onion,Carrots'),
	('Talapia Tacos','4','Fairly Easy',30,'Tilapia'),
	('Pesto Tomato Penne','3','Super Simple',20,'Pesto'),
	('Black Bean Soup','4','Fairly Easy',30,'Beans, Onions');